### ISSUE TITLE
WFDB2MAT does not generate files on some Windows Systems

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ikarosilva/wfdb-app-toolbox#102]
```
What steps will reproduce the problem?

 wfdb2mat('mitdb/200')

Is not able to create some mat-file. But there is no error message. System 
configuration:

 MATLAB_VERSION: '8.5.0.173394 (R2015a)'
              inOctave: 0
          WFDB_VERSION: '[10.5.24]'
                osName: 'windows'
            fullOsName: ' Windows 7'
                osArch: ' amd64'
        customArchFlag: ' false'
             OSVersion: ' 6.1'
            JVMVersion: ' 1.7.0_60]'
     WFDB_JAVA_VERSION: 'wfdb-app-JVM7-0-9-8.jar'
           DEBUG_LEVEL: 0
     NETWORK_WAIT_TIME: 1000
           MATLAB_ARCH: 'win64'
        WFDB_CUSTOMLIB: 0


This has been reported by a user, but we are currently not able to reproduce it.
The user suggested a work-around by reverting to version 0.9.7 of the toolbox.



```

Original issue reported on code.google.com by `ikarosil...@gmail.com` on 22 Jan 2015 at 3:03
